language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: dev